MyBookListMVC/Models/ApplicationDbContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyBookListMVC.Models
{
	public class ApplicationDbContext : DbContext
	{
		public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)
		{

		}

		public DbSet<Book>  Books { get; set; }
		public DbSet<UserClass> UserReg { get; set; }



	}
}

MyBookListMVC/Models/Book.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MyBookListMVC.Models
{
	public class Book
	{
		[Key]
		public int Id { get; set; }

		[Required]
		public string Name { get; set; }
		public string Author { get; set; }
		public string ISBN { get; set; }
		public float Price { get; set; }



	}
}

MyBookListMVC/Models/ErrorViewModel.cs
using System;

namespace MyBookListMVC.Models
{
	public class ErrorViewModel
	{
		public string RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

MyBookListMVC/Models/LogIn.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using Xunit;

namespace MyBookListMVC.Models
{
	public class LogIn
	{
		[Required(ErrorMessage = "Please enter your User name ")]
		[Display(Name = "Enter User name")]
		public string Username { get; set; }

		[Required(ErrorMessage = "Please enter you User name")]
		[DataType(DataType.Password)]
		[Display(Name = "Enter Password")]
		public string Pwd { get; set; }

		public bool IsLogged { get; set; }

	}
}

MyBookListMVC/Models/ReqauiredAttribute.cs
using System;

namespace MyBookListMVC.Models
{
	internal class ReqauiredAttribute : Attribute
	{
	}
}

MyBookListMVC/Models/UserClass.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace MyBookListMVC.Models
{
	public class UserClass
	{
		[Key]
		public int UserId { get; set; }

		[Required(ErrorMessage = "Username is required.")]
		[Display(Name="User name")]
		public string Username { get; set; }

		[Required(ErrorMessage = "Password is required.")]
		[DataType(DataType.Password)]
		[Display(Name = "Password")]
		public string Pwd { get; set; }

		[Required(ErrorMessage = "Confirm password is required.")]
		[Compare("Pwd", ErrorMessage = "Please confirm your password.")]
		[DataType(DataType.Password)]
		[Display(Name = "Confirm password")]
		public string Confirmpwd { get; set; }

		[Required(ErrorMessage = "Email is required.")]
		[Display(Name = "Email")]
		public string Uemail { get; set; }

		[Required(ErrorMessage = "Select the Gender.")]
		[Display(Name = "Gender")]
		public string  Gender { get; set; }

		[Required(ErrorMessage = "Select the Martial status.")]
		[Display(Name = "Martial Status")]
		public string Martialstatus { get; set; }
	}
}

MyBookListMVC/Controllers/BooksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBookListMVC.Models;

namespace MyBookListMVC.Controllers
{
    public class BooksController : Controller
    {
		private readonly ApplicationDbContext _db;
		[BindProperty]
		public Book Book { get; set; }

		public BooksController(ApplicationDbContext db)
		{
			_db = db;
		}

        public IActionResult Index()
        {
            return View();
        }

		public IActionResult Upsert(int? id)
		{
			Book = new Book();
			if (id==null)
			{
				//Create
				return View(Book);
			}
			// Update
			Book = _db.Books.FirstOrDefault(u => u.Id == id);
			if(Book == null)
			{
				return NotFound();
			}
			return View(Book);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Upsert()
		{
			if (ModelState.IsValid)
			{
				if (Book.Id == 0)
				{
					//Create
					_db.Books.Add(Book);
				}
				else
				{
					_db.Books.Update(Book);
				}
				_db.SaveChanges();
				return RedirectToAction("Index");
			}
			return View(Book);
		}

		#region API Calls
		[HttpGet]
		public async Task<IActionResult> GetAll()
		{
			return Json(new { data = await _db.Books.ToListAsync() });
		}

		[HttpDelete]
		public async Task<IActionResult> Delete(int id)
		{
			var bookFromDb = await _db.Books.FirstOrDefaultAsync(u => u.Id == id);
			if (bookFromDb == null)
			{
				return Json(new { success = false, message = "Error while Deleting" });
			}
			_db.Books.Remove(bookFromDb);
			await _db.SaveChangesAsync();
			return Json(new { success = true, message = "Delete successful" });
		}

		#endregion

	}
}

MyBookListMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MyBookListMVC.Models;

namespace MyBookListMVC.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

MyBookListMVC/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBookListMVC.Models;


namespace MyBookListMVC.Controllers
{
    public class LogInController : Controller
    {
			private readonly ApplicationDbContext _db;

			public LogInController(ApplicationDbContext db)
			{
				_db = db;
			}


        public IActionResult Index()
        {
            return View();
        }

		[HttpPost]
		public IActionResult Index(LogIn login)
		{
			var name = _db.UserReg.Select(x => x.Username).Where(x => x == login.Username).FirstOrDefault();
			var password = _db.UserReg.Select(x => x.Pwd).Where(x => x == login.Pwd).FirstOrDefault();
			if (name != null && password != null)
			{
				login.IsLogged = true;
				return RedirectToAction("Index","Books");
			}
			ViewBag.message = "The User " + login.Username + " or the password is invalid!";
			return View();
		}
	}
}

MyBookListMVC/Controllers/UserRegistrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyBookListMVC.Models;


namespace MyBookListMVC.Controllers
{
	public class UserRegistrationController : Controller
	{
		private readonly ApplicationDbContext _db;


		public UserRegistrationController(ApplicationDbContext db)
		{
			_db = db;
		}

		public IActionResult Index()
		{
			return View();
		}
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(UserClass UserReg)
		{
			var Name = _db.UserReg.Select(x => x.Username).Where(x => x == UserReg.Username).FirstOrDefault();
			var Email = _db.UserReg.Select(x => x.Uemail).Where(x => x == UserReg.Uemail).FirstOrDefault();

			if (Name == null && Email == null)
			{
				_db.Add(UserReg);
				_db.SaveChanges();
				ViewBag.message = "The User " + UserReg.Username + " is Saved Successfully.";
				return View();
			}
			else
			{
				ViewBag.message = "The User " + UserReg.Username + " is already exist or the email "+ UserReg.Uemail + " is already used!";
				return View();
			}


		}



	}
}

MyBookListMVC/Views/Books/Index.cshtml
@model MyBookListMVC.Models.Book

<br />
<div class="container row p-0 m-0">
    <div class="col-6">
        <h2 class="text-info">Book List</h2>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="col-3 offset-3">
        <a asp-action="Upsert" asp-controller="Books" class="btn btn-info form-control text-white">
            Add New Book
        </a>
    </div>
    <div class="col-12 border p-3">
        <table id="DT_load" class="table table-striped table-bordered" style="width:100%">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Author</th>
                    <th>ISBN</th>
                    <th>Price</th>
                    <th></th>
                </tr>
            </thead>
        </table>
    </div>
</div>

@section Scripts{
    <script src="~/js/bookList.js"></script>
}

MyBookListMVC/Views/Books/Upsert.cshtml
@model MyBookListMVC.Models.Book

<br />
<h2 class="text-info">@(Model.Id != 0 ? "Edit" : "Create") Book</h2>
<br />

<div class="border container" style="padding:30px;">
    <form method="post">
        @if (Model.Id != 0)
        {
            <input type="hidden" asp-for="Id" />
        }
        <div class="text-danger" asp-validation-summary="ModelOnly"></div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Name"></label>
            </div>
            <div class="col-6">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Author"></label>
            </div>
            <div class="col-6">
                <input asp-for="Author" class="form-control" />
                <span asp-validation-for="Author" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="ISBN"></label>
            </div>
            <div class="col-6">
                <input asp-for="ISBN" class="form-control" />
                <span asp-validation-for="ISBN" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3">
                <label asp-for="Price"></label>
            </div>
            <div class="col-6">
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-3 offset-3">
                <button type="submit" class="btn btn-primary form-control">
                    @(Model.Id != 0 ? "Update" : "Create")
                </button>
            </div>
            <div class="col-3">
                <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
            </div>
        </div>
    </form>
</div>

@section Scripts{
<partial name="_ValidationScriptsPartial"/>
 }

MyBookListMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MyBookListMVC/Views/LogIn/Index.cshtml
@model MyBookListMVC.Models.LogIn

@{
    ViewData["Title"] = "Log In";
}



<h2>Log In</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Index">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pwd" class="control-label"></label>
                <input asp-for="Pwd" class="form-control" type="password" />
                <span asp-validation-for="Pwd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Log In" class="btn btn-primary" />
                <a class="btn btn-info" asp-controller="UserRegistration" asp-action="Create">Registration</a>
            </div>
            <b>@ViewBag.message</b>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyBookListMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]MyBookListMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">List of Books</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LogIn" asp-action="Index">Log In</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="UserRegistration" asp-action="Create">Registration</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Books" asp-action="Index">Book List</a>
                        </li>
                    </ul>

                </div>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - My Book List MVC 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

MyBookListMVC/Views/UserRegistration/Create.cshtml
@model MyBookListMVC.Models.UserClass

@{
    ViewData["Title"] = "Create";

}

<h2>Registration form</h2>


<hr />
<div class="row">
    <div class="col-md-9">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Username" class="control-label"></label>
                <input asp-for="Username" class="form-control" />
                <span asp-validation-for="Username" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pwd" class="control-label"></label>
                <input asp-for="Pwd" class="form-control" type="password" />
                <span asp-validation-for="Pwd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Confirmpwd" class="control-label"></label>
                <input asp-for="Confirmpwd" class="form-control" type="password" />
                <span asp-validation-for="Confirmpwd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Uemail" class="control-label"></label>
                <input asp-for="Uemail" class="form-control" />
                <span asp-validation-for="Uemail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                @*<input asp-for="Gender" class="form-control" />*@

                <input type="radio" name="Gender" value="M" />Male
                <input type="radio" name="Gender" value="F" />Female

                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Martialstatus" class="control-label"></label>
                

                <select asp-for="Martialstatus">
                    <option selected disabled>-- Select Martial Status --</option>
                    <option>Married</option>
                    <option>Unmaried</option>
                    <option>Widow</option>
                </select>

                <span asp-validation-for="Martialstatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save User Record" class="btn btn-primary" />
            </div>
            <b>@ViewBag.message</b>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}